### PR TITLE
Package ece2cmor3 for installation with pip

### PR DESCRIPTION
**Pull request by jmrgonza**
Project has been refactored into a top level python package named ece2cmor3.
To create a source distribution to be installed with pip:
`python setup.py sdist`
`pip install dist/ece2cmor3-$VERSION.tar.gz`

### CODE REVIEW

**Comment by jmrgonza** [comment]
Hi Gijs,

I did the manual merge with the trunk yesterday, but foud that the tests 
that you implemented with the Travis tool were failing. I was 
investigating the problem in my computer. The version that I commited 
before going on holidays was passing all the tests.
There are also some decisions to make about version numbers, developer 
email (I'm not sure if you want your email to be published with the 
package) and some urls that need to be changed.
Cheers,

Chema

**Comment by goord** [comment]
Hi Chema, I will have a look at it too. I think it is the cmor library version which is causing this

**Comment by jmrgonza** [comment]
That was my first guess also. I had problems with cmor-3.2.4, and so I 
kept using cmor-3.2.3. I think that with the latest trunk it was 
upgraded to cmor-3.2.5, that I haven´t tested.

**Comment by goord** [comment]
I updated the cmip table revision and now the tests run ok. The contact and other metadata are all fine for me, the only thing I am missing are dependencies, should these also be listed in the setup.py?

**Comment by jmrgonza** [comment]
Hi Gijs,

in a previous version of setup.py I used a function to read the 
requirements.txt file to get the dependencies information. This works OK 
if you only plan to distribute the package with pip.
The problem comes when you want to use conda, since que conda installer 
prefers all the dependencies to be conda packages. These dependencies 
are listed in the meta.yaml file. I found problems with the conda 
builder I had references to pip packages in the setup.py file, so I 
decided to drop them.
If you want to build a pip package with dependency information, I can 
put back the line where the requirements.txt file is read in setup.py (I 
would put it in comments, to avoid problems with the conda builder). 
Another option would be to build the pip package without dependency 
information, and instruct the users to run a 'pip -r requirements.txt' 
command before installation.
I'm glad that the link to the cmip tables repository works, since moving 
them to another directory was the part of the package refactoring that 
caused me more trouble.
Greetings,

Chema

**Comment by goord** [comment]
Ok then it's fine like it is now, we just adapt the README for installation from source.

**Pull request merged**
